### ISSUE TITLE
The mass order in QuarkMasses LeptonMasses etc.

### ISSUE THREAD

**Issue by ycwu1030** [phbasler/BSMPT#98]
Hi:
   In `ClassPotentialOrigin`, the `ComplexEigenSolver` is used to obtain the mass eigenvalues of quarks and leptons. However, in Eigen's docs, it is said that in `ComplexEigenSolver`, the eigenvalues are not sorted in any particular order. So that means, it is not guaranteed that i.e. the top mass is the last entry. Is there any particular reason to assume the top quark is the last entry and you didn't do any further sortings? Thanks!

Best
ycwu

**Comment by phbasler** [comment]
Hi @ycwu1030 ,

It is actually good that there is no sorting of the eigenvalues. In cases where we want the `ComplexEigenSolver` we are interested in the complex phases of a certain particle and if there is no sorting, then we know that the order of the eigenvalues is the same as  our basis. So if you choose the basis `[u,c,t]` then you will get `[m_u,m_c,m_t]` but if you choose `[u,t,c]` for your model, then you will get `[m_u,m_t,m_c]`. 

In the cases where we use the `SelfAdjointEigenSolver`, which sorts ascending, we do not care about the order because we sum over all of them, e.g. https://github.com/phbasler/BSMPT/blob/master/src/models/ClassPotentialOrigin.cpp#L3030.

But we should probably add this info to the documentation so that everyone is aware of that.

**Comment by ycwu1030** [comment]
Hi:
   Thanks for pointing out this. I though that by 'not sorted in any particular order' they mean the output eigensystem can be in any order, like in some case, it will preserve the order, but in some other case (by changing input values for the matrix), the order may change. And I also have a brief check, the input order is (d, s, b, u, c, t), the out put order become ( u, d, s, c, b, t ). So I'm still not sure about the order.

**Comment by phbasler** [comment]
I added a test in the https://github.com/phbasler/BSMPT/tree/ComplexEigenSolverOrdering branch ( https://github.com/phbasler/BSMPT/blob/ComplexEigenSolverOrdering/tests/unittests/Test-c2hdm.cpp#L421-L431 ) . I changed the quark masases ( https://github.com/phbasler/BSMPT/blob/ComplexEigenSolverOrdering/include/BSMPT/models/SMparam.h#L174-L186 ) so that everyone has a different mass and the output of the test is always mass ordered for me. 
Can you run 
`cmake --build build -t GenericTests -j8 && build/bin/GenericTests "[order]" ` and copy the output?

**Comment by ycwu1030** [comment]
Hi:
   Thanks for this test! Yes, in the output, I got the mass in order (u,d,s,c,b,t) as I said in my last comment. But what I thought, by checking the Curvature_Quark_F2H1 in C2HDM, at least, you group (u,c,t) and (d, s, b) together. So this means the order actually is changed, althougth, the output order is the desired one. What I concerned is that since this changes the order, then when we consider finite temperature case, there might be some case, the order will change again to the one we don't expected.

**Comment by phbasler** [comment]
Yes we group them together. Here you can read it maybe more easily in the [c2hdm description](https://phbasler.github.io/BSMPT/documentation/classBSMPT_1_1Models_1_1Class__Potential__C2HDM.html)

The only place where we actually care about the ordering of the values is [here](https://github.com/phbasler/BSMPT/blob/master/src/baryo_calculation/transport_equations.cpp#L314-L338), so the worst case that can happen is that we have incorrect phases during the EWBG calculation.
As the ewbg calculation is only implemented for the c2hdm, we can assume there that the top is the heaviest quark and the bottom the seoncd heaviest. Also that the tau is the heaviest lepton.
The distinction between bottom and top could swap, if tan(beta) at finite temperature is somewhere about 1000, (m_t/m_b)^2, which we never achieved for a SFOEWPT. 

To assure the current behaviour is not changed if you use a different eigen version, we should probably add a `QuarkMassesSorted` function which just sorts the eigenvalues by absolute value and use this in the phase calculation.

But we should add some fallbacks/ be more verbose with the errors for the following scenarios
- What happens if top and bottom swap place?
- The code won't work in a model where you put leptons and quarks in one matrix. We either need to add a warning that this part only works in the c2hdm or make it more general.
- The code won't work if you add another quark to your model which is heavier then the top. Here again we should throw an exception that this only works in the c2hdm.

Can you think of another scenario where this might

**Comment by ycwu1030** [comment]
Thanks for the detailed explanations! I think you list the most important cases.
